/**
 * @module config
 * @description Backward-compatible configuration object re-exported from {@link module:constants}.
 * Prefer importing named constants from `./constants.js` in new code.
 */

import {
    IDLE_TIMEOUT_MS,
    MAX_SESSION_TIME_MS,
    MAX_WAIT_TIME_MS,
    CONNECT_TIMEOUT_MS,
    DEFER_WAIT_TIME_MS,
    WS_CONNECTION_TIMEOUT_MS,
    WS_PING_INTERVAL_MULTIPLIER,
    WS_COMMAND_DELAY_MS,
    BROWSER_WAIT_AFTER_START_MS,
    BROWSER_WAIT_AFTER_STOP_MS,
    BROWSER_PROCESS_CLEANUP_MS,
    BROWSER_INITIAL_DATA_WAIT_MS,
    BROWSER_EXTRA_WAIT_MS,
    BROWSER_RECONNECT_WAIT_MS,
    INTER_ACCOUNT_DELAY_MS,
    TERMINAL_FULL_RETRY_DELAY_MS,
    MAX_RETRY_ATTEMPTS,
    MAX_DEFER_CYCLES,
    BRAIN_RESPONSE_TIMEOUT_MS,
    DEFAULT_MAX_USERS,
    SLOT_CHECK_INTERVAL_MS,
    SERVER_LIST_CONTEXT_CHARS
} from './constants.js';

/** @type {Object} Runtime configuration (values sourced from constants.js) */
export const config = {
    IDLE_TIMEOUT_MS,
    MAX_SESSION_TIME_MS,
    MAX_WAIT_TIME_MS,
    CONNECT_TIMEOUT_MS,
    DEFER_WAIT_TIME_MS,
    WS_CONNECTION_TIMEOUT_MS,
    WS_PING_INTERVAL_MULTIPLIER,
    WS_COMMAND_DELAY_MS,
    BROWSER_WAIT_AFTER_START_MS,
    BROWSER_WAIT_AFTER_STOP_MS,
    BROWSER_PROCESS_CLEANUP_MS,
    BROWSER_INITIAL_DATA_WAIT_MS,
    BROWSER_EXTRA_WAIT_MS,
    BROWSER_RECONNECT_WAIT_MS,
    ACCOUNT_DELAY_MS: INTER_ACCOUNT_DELAY_MS,
    TERMINAL_FULL_RETRY_DELAY_MS,
    MAX_RETRY_ATTEMPTS,
    MAX_DEFER_CYCLES,
    BRAIN_RESPONSE_TIMEOUT_MS,
    DEFAULT_MAX_USERS,
    SLOT_CHECK_INTERVAL_MS,
    SERVER_LIST_CONTEXT_CHARS
};
